version: '2'
services:
  generate-proto:
    container_name: johnny-proto-generator
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "
        echo 'Generate TS proto files'
        rm -rf ./proto_out/pbjs && 
        mkdir -p ./proto_out/pbjs && 
        pbjs --target static-module -p js --wrap commonjs --keep-case -o ./proto_out/pbjs/compiled.js ./proto/*
        pbts -o proto_out/pbjs/compiled.d.ts ./proto_out/pbjs/compiled.js        

        echo 'Generate dart proto files'
        rm -rf ./proto_out/dart/lib
        mkdir -p ./proto_out/dart/lib
        /usr/lib/dart/bin/pub --version
        protoc --dart_out=./proto_out/dart/lib ./proto/* --plugin=protoc-gen-dart=/root/.pub-cache/bin/protoc-gen-dart
      "
    volumes: 
      - ./workdir/:/usr/src/app
